//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for CatalogImage
void main() {
  // final instance = CatalogImage();

  group('test CatalogImage', () {
    // The internal name to identify this image in calls to the Square API. This is a searchable attribute for use in applicable query filters using the [SearchCatalogObjects](https://developer.squareup.com/reference/square_2023-12-13/catalog-api/search-catalog-objects). It is not unique and should not be shown in a buyer facing context.
    // String name
    test('to test the property `name`', () async {
      // TODO
    });

    // The URL of this image, generated by Square after an image is uploaded using the [CreateCatalogImage](https://developer.squareup.com/reference/square_2023-12-13/catalog-api/create-catalog-image) endpoint. To modify the image, use the UpdateCatalogImage endpoint. Do not change the URL field.
    // String url
    test('to test the property `url`', () async {
      // TODO
    });

    // A caption that describes what is shown in the image. Displayed in the Square Online Store. This is a searchable attribute for use in applicable query filters using the [SearchCatalogObjects](https://developer.squareup.com/reference/square_2023-12-13/catalog-api/search-catalog-objects).
    // String caption
    test('to test the property `caption`', () async {
      // TODO
    });

    // The immutable order ID for this image object created by the Photo Studio service in Square Online Store.
    // String photoStudioOrderId
    test('to test the property `photoStudioOrderId`', () async {
      // TODO
    });
  });
}
