//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for Checkout
void main() {
  // final instance = Checkout();

  group('test Checkout', () {
    // ID generated by Square Checkout when a new checkout is requested.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The URL that the buyer's browser should be redirected to after the checkout is completed.
    // String checkoutPageUrl
    test('to test the property `checkoutPageUrl`', () async {
      // TODO
    });

    // If `true`, Square Checkout will collect shipping information on your behalf and store that information with the transaction information in your Square Dashboard.  Default: `false`.
    // bool askForShippingAddress
    test('to test the property `askForShippingAddress`', () async {
      // TODO
    });

    // The email address to display on the Square Checkout confirmation page and confirmation email that the buyer can use to contact the merchant.  If this value is not set, the confirmation page and email will display the primary email address associated with the merchant's Square account.  Default: none; only exists if explicitly set.
    // String merchantSupportEmail
    test('to test the property `merchantSupportEmail`', () async {
      // TODO
    });

    // If provided, the buyer's email is pre-populated on the checkout page as an editable text field.  Default: none; only exists if explicitly set.
    // String prePopulateBuyerEmail
    test('to test the property `prePopulateBuyerEmail`', () async {
      // TODO
    });

    // Address prePopulateShippingAddress
    test('to test the property `prePopulateShippingAddress`', () async {
      // TODO
    });

    // The URL to redirect to after checkout is completed with `checkoutId`, Square's `orderId`, `transactionId`, and `referenceId` appended as URL parameters. For example, if the provided redirect_url is `http://www.example.com/order-complete`, a successful transaction redirects the customer to:  <pre><code>http://www.example.com/order-complete?checkoutId=xxxxxx&amp;orderId=xxxxxx&amp;referenceId=xxxxxx&amp;transactionId=xxxxxx</code></pre>  If you do not provide a redirect URL, Square Checkout will display an order confirmation page on your behalf; however Square strongly recommends that you provide a redirect URL so you can verify the transaction results and finalize the order through your existing/normal confirmation workflow.
    // String redirectUrl
    test('to test the property `redirectUrl`', () async {
      // TODO
    });

    // Order order
    test('to test the property `order`', () async {
      // TODO
    });

    // The time when the checkout was created, in RFC 3339 format.
    // String createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

    // Additional recipients (other than the merchant) receiving a portion of this checkout. For example, fees assessed on the purchase by a third party integration.
    // List<AdditionalRecipient> additionalRecipients (default value: const [])
    test('to test the property `additionalRecipients`', () async {
      // TODO
    });
  });
}
