//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for CreateCardRequest
void main() {
  // final instance = CreateCardRequest();

  group('test CreateCardRequest', () {
    // A unique string that identifies this CreateCard request. Keys can be any valid string and must be unique for every request.  Max: 45 characters  See [Idempotency keys](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency) for more information.
    // String idempotencyKey
    test('to test the property `idempotencyKey`', () async {
      // TODO
    });

    // The ID of the source which represents the card information to be stored. This can be a card nonce or a payment id.
    // String sourceId
    test('to test the property `sourceId`', () async {
      // TODO
    });

    // An identifying token generated by [Payments.verifyBuyer()](https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer). Verification tokens encapsulate customer device information and 3-D Secure challenge results to indicate that Square has verified the buyer identity.  See the [SCA Overview](https://developer.squareup.com/docs/sca-overview).
    // String verificationToken
    test('to test the property `verificationToken`', () async {
      // TODO
    });

    // Card card
    test('to test the property `card`', () async {
      // TODO
    });
  });
}
