//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for Dispute
void main() {
  // final instance = Dispute();

  group('test Dispute', () {
    // The unique ID for this `Dispute`, generated by Square.
    // String disputeId
    test('to test the property `disputeId`', () async {
      // TODO
    });

    // The unique ID for this `Dispute`, generated by Square.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // Money amountMoney
    test('to test the property `amountMoney`', () async {
      // TODO
    });

    // The reason why the cardholder initiated the dispute.
    // String reason
    test('to test the property `reason`', () async {
      // TODO
    });

    // The current state of this dispute.
    // String state
    test('to test the property `state`', () async {
      // TODO
    });

    // The deadline by which the seller must respond to the dispute, in [RFC 3339 format](https://developer.squareup.com/docs/build-basics/common-data-types/working-with-dates).
    // String dueAt
    test('to test the property `dueAt`', () async {
      // TODO
    });

    // DisputedPayment disputedPayment
    test('to test the property `disputedPayment`', () async {
      // TODO
    });

    // The IDs of the evidence associated with the dispute.
    // List<String> evidenceIds (default value: const [])
    test('to test the property `evidenceIds`', () async {
      // TODO
    });

    // The card brand used in the disputed payment.
    // String cardBrand
    test('to test the property `cardBrand`', () async {
      // TODO
    });

    // The timestamp when the dispute was created, in RFC 3339 format.
    // String createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

    // The timestamp when the dispute was last updated, in RFC 3339 format.
    // String updatedAt
    test('to test the property `updatedAt`', () async {
      // TODO
    });

    // The ID of the dispute in the card brand system, generated by the card brand.
    // String brandDisputeId
    test('to test the property `brandDisputeId`', () async {
      // TODO
    });

    // The timestamp when the dispute was reported, in RFC 3339 format.
    // String reportedDate
    test('to test the property `reportedDate`', () async {
      // TODO
    });

    // The timestamp when the dispute was reported, in RFC 3339 format.
    // String reportedAt
    test('to test the property `reportedAt`', () async {
      // TODO
    });

    // The current version of the `Dispute`.
    // int version
    test('to test the property `version`', () async {
      // TODO
    });

    // The ID of the location where the dispute originated.
    // String locationId
    test('to test the property `locationId`', () async {
      // TODO
    });
  });
}
