//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for InventoryAdjustment
void main() {
  // final instance = InventoryAdjustment();

  group('test InventoryAdjustment', () {
    // A unique ID generated by Square for the `InventoryAdjustment`.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // An optional ID provided by the application to tie the `InventoryAdjustment` to an external system.
    // String referenceId
    test('to test the property `referenceId`', () async {
      // TODO
    });

    // The [inventory state](https://developer.squareup.com/reference/square_2023-12-13/enums/InventoryState) of the related quantity of items before the adjustment.
    // String fromState
    test('to test the property `fromState`', () async {
      // TODO
    });

    // The [inventory state](https://developer.squareup.com/reference/square_2023-12-13/enums/InventoryState) of the related quantity of items after the adjustment.
    // String toState
    test('to test the property `toState`', () async {
      // TODO
    });

    // The Square-generated ID of the [Location](https://developer.squareup.com/reference/square_2023-12-13/objects/Location) where the related quantity of items is being tracked.
    // String locationId
    test('to test the property `locationId`', () async {
      // TODO
    });

    // The Square-generated ID of the [CatalogObject](https://developer.squareup.com/reference/square_2023-12-13/objects/CatalogObject) being tracked.
    // String catalogObjectId
    test('to test the property `catalogObjectId`', () async {
      // TODO
    });

    // The [type](https://developer.squareup.com/reference/square_2023-12-13/enums/CatalogObjectType) of the [CatalogObject](https://developer.squareup.com/reference/square_2023-12-13/objects/CatalogObject) being tracked.   The Inventory API supports setting and reading the `\"catalog_object_type\": \"ITEM_VARIATION\"` field value.  In addition, it can also read the `\"catalog_object_type\": \"ITEM\"` field value that is set by the Square Restaurants app.
    // String catalogObjectType
    test('to test the property `catalogObjectType`', () async {
      // TODO
    });

    // The number of items affected by the adjustment as a decimal string. Can support up to 5 digits after the decimal point.
    // String quantity
    test('to test the property `quantity`', () async {
      // TODO
    });

    // Money totalPriceMoney
    test('to test the property `totalPriceMoney`', () async {
      // TODO
    });

    // A client-generated RFC 3339-formatted timestamp that indicates when the inventory adjustment took place. For inventory adjustment updates, the `occurred_at` timestamp cannot be older than 24 hours or in the future relative to the time of the request.
    // String occurredAt
    test('to test the property `occurredAt`', () async {
      // TODO
    });

    // An RFC 3339-formatted timestamp that indicates when the inventory adjustment is received.
    // String createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

    // SourceApplication source_
    test('to test the property `source_`', () async {
      // TODO
    });

    // The Square-generated ID of the [Employee](https://developer.squareup.com/reference/square_2023-12-13/objects/Employee) responsible for the inventory adjustment.
    // String employeeId
    test('to test the property `employeeId`', () async {
      // TODO
    });

    // The Square-generated ID of the [Team Member](https://developer.squareup.com/reference/square_2023-12-13/objects/TeamMember) responsible for the inventory adjustment.
    // String teamMemberId
    test('to test the property `teamMemberId`', () async {
      // TODO
    });

    // The Square-generated ID of the [Transaction](https://developer.squareup.com/reference/square_2023-12-13/objects/Transaction) that caused the adjustment. Only relevant for payment-related state transitions.
    // String transactionId
    test('to test the property `transactionId`', () async {
      // TODO
    });

    // The Square-generated ID of the [Refund](https://developer.squareup.com/reference/square_2023-12-13/objects/Refund) that caused the adjustment. Only relevant for refund-related state transitions.
    // String refundId
    test('to test the property `refundId`', () async {
      // TODO
    });

    // The Square-generated ID of the purchase order that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
    // String purchaseOrderId
    test('to test the property `purchaseOrderId`', () async {
      // TODO
    });

    // The Square-generated ID of the goods receipt that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
    // String goodsReceiptId
    test('to test the property `goodsReceiptId`', () async {
      // TODO
    });

    // InventoryAdjustmentGroup adjustmentGroup
    test('to test the property `adjustmentGroup`', () async {
      // TODO
    });
  });
}
