//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for InventoryAdjustmentGroup
void main() {
  // final instance = InventoryAdjustmentGroup();

  group('test InventoryAdjustmentGroup', () {
    // A unique ID generated by Square for the `InventoryAdjustmentGroup`.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The inventory adjustment of the composed variation.
    // String rootAdjustmentId
    test('to test the property `rootAdjustmentId`', () async {
      // TODO
    });

    // Representative `from_state` for adjustments within the group. For example, for a group adjustment from `IN_STOCK` to `SOLD`, there can be two component adjustments in the group: one from `IN_STOCK`to `COMPOSED` and the other one from `COMPOSED` to `SOLD`. Here, the representative `from_state` for the `InventoryAdjustmentGroup` is `IN_STOCK`.
    // String fromState
    test('to test the property `fromState`', () async {
      // TODO
    });

    // Representative `to_state` for adjustments within group. For example, for a group adjustment from `IN_STOCK` to `SOLD`, the two component adjustments in the group can be from `IN_STOCK` to `COMPOSED` and from `COMPOSED` to `SOLD`. Here, the representative `to_state` of the `InventoryAdjustmentGroup` is `SOLD`.
    // String toState
    test('to test the property `toState`', () async {
      // TODO
    });
  });
}
