//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for LoyaltyEvent
void main() {
  // final instance = LoyaltyEvent();

  group('test LoyaltyEvent', () {
    // The Square-assigned ID of the loyalty event.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The type of the loyalty event.
    // String type
    test('to test the property `type`', () async {
      // TODO
    });

    // The timestamp when the event was created, in RFC 3339 format.
    // String createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

    // LoyaltyEventAccumulatePoints accumulatePoints
    test('to test the property `accumulatePoints`', () async {
      // TODO
    });

    // LoyaltyEventCreateReward createReward
    test('to test the property `createReward`', () async {
      // TODO
    });

    // LoyaltyEventRedeemReward redeemReward
    test('to test the property `redeemReward`', () async {
      // TODO
    });

    // LoyaltyEventDeleteReward deleteReward
    test('to test the property `deleteReward`', () async {
      // TODO
    });

    // LoyaltyEventAdjustPoints adjustPoints
    test('to test the property `adjustPoints`', () async {
      // TODO
    });

    // The ID of the [loyalty account](https://developer.squareup.com/reference/square_2023-12-13/objects/LoyaltyAccount) associated with the event.
    // String loyaltyAccountId
    test('to test the property `loyaltyAccountId`', () async {
      // TODO
    });

    // The ID of the [location](https://developer.squareup.com/reference/square_2023-12-13/objects/Location) where the event occurred.
    // String locationId
    test('to test the property `locationId`', () async {
      // TODO
    });

    // Defines whether the event was generated by the Square Point of Sale.
    // String source_
    test('to test the property `source_`', () async {
      // TODO
    });

    // LoyaltyEventExpirePoints expirePoints
    test('to test the property `expirePoints`', () async {
      // TODO
    });

    // LoyaltyEventOther otherEvent
    test('to test the property `otherEvent`', () async {
      // TODO
    });

    // LoyaltyEventAccumulatePromotionPoints accumulatePromotionPoints
    test('to test the property `accumulatePromotionPoints`', () async {
      // TODO
    });
  });
}
