//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for OrderFulfillmentFulfillmentEntry
void main() {
  // final instance = OrderFulfillmentFulfillmentEntry();

  group('test OrderFulfillmentFulfillmentEntry', () {
    // A unique ID that identifies the fulfillment entry only within this order.
    // String uid
    test('to test the property `uid`', () async {
      // TODO
    });

    // The `uid` from the order line item.
    // String lineItemUid
    test('to test the property `lineItemUid`', () async {
      // TODO
    });

    // The quantity of the line item being fulfilled, formatted as a decimal number. For example, `\"3\"`. Fulfillments for line items with a `quantity_unit` can have non-integer quantities. For example, `\"1.70000\"`.
    // String quantity
    test('to test the property `quantity`', () async {
      // TODO
    });

    // Application-defined data attached to this fulfillment entry. Metadata fields are intended to store descriptive references or associations with an entity in another system or store brief information about the object. Square does not process this field; it only stores and returns it in relevant API calls. Do not use metadata to store any sensitive information (such as personally identifiable information or card details). Keys written by applications must be 60 characters or less and must be in the character set `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed with a namespace, separated from the key with a ':' character. Values have a maximum length of 255 characters. An application can have up to 10 entries per metadata field. Entries written by applications are private and can only be read or modified by the same application. For more information, see [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    // Map<String, String> metadata (default value: const {})
    test('to test the property `metadata`', () async {
      // TODO
    });
  });
}
