//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for RetrieveGiftCardFromNonceRequest
void main() {
  // final instance = RetrieveGiftCardFromNonceRequest();

  group('test RetrieveGiftCardFromNonceRequest', () {
    // The payment token of the gift card to retrieve. Payment tokens are generated by the  Web Payments SDK or In-App Payments SDK.
    // String nonce
    test('to test the property `nonce`', () async {
      // TODO
    });
  });
}
