//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for SaveCardOptions
void main() {
  // final instance = SaveCardOptions();

  group('test SaveCardOptions', () {
    // The square-assigned ID of the customer linked to the saved card.
    // String customerId
    test('to test the property `customerId`', () async {
      // TODO
    });

    // The id of the created card-on-file.
    // String cardId
    test('to test the property `cardId`', () async {
      // TODO
    });

    // An optional user-defined reference ID that can be used to associate this `Card` to another entity in an external system. For example, a customer ID generated by a third-party system.
    // String referenceId
    test('to test the property `referenceId`', () async {
      // TODO
    });
  });
}
