//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:square_dart_sdk/api.dart';
import 'package:test/test.dart';

// tests for Transaction
void main() {
  // final instance = Transaction();

  group('test Transaction', () {
    // The transaction's unique ID, issued by Square payments servers.
    // String id
    test('to test the property `id`', () async {
      // TODO
    });

    // The ID of the transaction's associated location.
    // String locationId
    test('to test the property `locationId`', () async {
      // TODO
    });

    // The timestamp for when the transaction was created, in RFC 3339 format.
    // String createdAt
    test('to test the property `createdAt`', () async {
      // TODO
    });

    // The tenders used to pay in the transaction.
    // List<Tender> tenders (default value: const [])
    test('to test the property `tenders`', () async {
      // TODO
    });

    // Refunds that have been applied to any tender in the transaction.
    // List<Refund> refunds (default value: const [])
    test('to test the property `refunds`', () async {
      // TODO
    });

    // If the transaction was created with the [Charge](https://developer.squareup.com/reference/square_2023-12-13/transactions-api/charge) endpoint, this value is the same as the value provided for the `reference_id` parameter in the request to that endpoint. Otherwise, it is not set.
    // String referenceId
    test('to test the property `referenceId`', () async {
      // TODO
    });

    // The Square product that processed the transaction.
    // String product
    test('to test the property `product`', () async {
      // TODO
    });

    // If the transaction was created in the Square Point of Sale app, this value is the ID generated for the transaction by Square Point of Sale.  This ID has no relationship to the transaction's canonical `id`, which is generated by Square's backend servers. This value is generated for bookkeeping purposes, in case the transaction cannot immediately be completed (for example, if the transaction is processed in offline mode).  It is not currently possible with the Connect API to perform a transaction lookup by this value.
    // String clientId
    test('to test the property `clientId`', () async {
      // TODO
    });

    // Address shippingAddress
    test('to test the property `shippingAddress`', () async {
      // TODO
    });

    // The order_id is an identifier for the order associated with this transaction, if any.
    // String orderId
    test('to test the property `orderId`', () async {
      // TODO
    });
  });
}
