//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class InventoryAdjustmentGroup {
  /// Returns a new [InventoryAdjustmentGroup] instance.
  InventoryAdjustmentGroup({
    this.id,
    this.rootAdjustmentId,
    this.fromState,
    this.toState,
  });

  /// A unique ID generated by Square for the `InventoryAdjustmentGroup`.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? id;

  /// The inventory adjustment of the composed variation.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? rootAdjustmentId;

  /// Representative `from_state` for adjustments within the group. For example, for a group adjustment from `IN_STOCK` to `SOLD`, there can be two component adjustments in the group: one from `IN_STOCK`to `COMPOSED` and the other one from `COMPOSED` to `SOLD`. Here, the representative `from_state` for the `InventoryAdjustmentGroup` is `IN_STOCK`.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? fromState;

  /// Representative `to_state` for adjustments within group. For example, for a group adjustment from `IN_STOCK` to `SOLD`, the two component adjustments in the group can be from `IN_STOCK` to `COMPOSED` and from `COMPOSED` to `SOLD`. Here, the representative `to_state` of the `InventoryAdjustmentGroup` is `SOLD`.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? toState;

  @override
  bool operator ==(Object other) => identical(this, other) || other is InventoryAdjustmentGroup &&
    other.id == id &&
    other.rootAdjustmentId == rootAdjustmentId &&
    other.fromState == fromState &&
    other.toState == toState;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (id == null ? 0 : id!.hashCode) +
    (rootAdjustmentId == null ? 0 : rootAdjustmentId!.hashCode) +
    (fromState == null ? 0 : fromState!.hashCode) +
    (toState == null ? 0 : toState!.hashCode);

  @override
  String toString() => 'InventoryAdjustmentGroup[id=$id, rootAdjustmentId=$rootAdjustmentId, fromState=$fromState, toState=$toState]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.id != null) {
      json[r'id'] = this.id;
    } else {
      json[r'id'] = null;
    }
    if (this.rootAdjustmentId != null) {
      json[r'root_adjustment_id'] = this.rootAdjustmentId;
    } else {
      json[r'root_adjustment_id'] = null;
    }
    if (this.fromState != null) {
      json[r'from_state'] = this.fromState;
    } else {
      json[r'from_state'] = null;
    }
    if (this.toState != null) {
      json[r'to_state'] = this.toState;
    } else {
      json[r'to_state'] = null;
    }
    return json;
  }

  /// Returns a new [InventoryAdjustmentGroup] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static InventoryAdjustmentGroup? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "InventoryAdjustmentGroup[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "InventoryAdjustmentGroup[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return InventoryAdjustmentGroup(
        id: mapValueOfType<String>(json, r'id'),
        rootAdjustmentId: mapValueOfType<String>(json, r'root_adjustment_id'),
        fromState: mapValueOfType<String>(json, r'from_state'),
        toState: mapValueOfType<String>(json, r'to_state'),
      );
    }
    return null;
  }

  static List<InventoryAdjustmentGroup> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <InventoryAdjustmentGroup>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = InventoryAdjustmentGroup.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, InventoryAdjustmentGroup> mapFromJson(dynamic json) {
    final map = <String, InventoryAdjustmentGroup>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = InventoryAdjustmentGroup.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of InventoryAdjustmentGroup-objects as value to a dart map
  static Map<String, List<InventoryAdjustmentGroup>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<InventoryAdjustmentGroup>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = InventoryAdjustmentGroup.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

