//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class InventoryAdjustment {
  /// Returns a new [InventoryAdjustment] instance.
  InventoryAdjustment({
    this.id,
    this.referenceId,
    this.fromState,
    this.toState,
    this.locationId,
    this.catalogObjectId,
    this.catalogObjectType,
    this.quantity,
    this.totalPriceMoney,
    this.occurredAt,
    this.createdAt,
    this.source_,
    this.employeeId,
    this.teamMemberId,
    this.transactionId,
    this.refundId,
    this.purchaseOrderId,
    this.goodsReceiptId,
    this.adjustmentGroup,
  });

  /// A unique ID generated by Square for the `InventoryAdjustment`.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? id;

  /// An optional ID provided by the application to tie the `InventoryAdjustment` to an external system.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? referenceId;

  /// The [inventory state](https://developer.squareup.com/reference/square_2023-12-13/enums/InventoryState) of the related quantity of items before the adjustment.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? fromState;

  /// The [inventory state](https://developer.squareup.com/reference/square_2023-12-13/enums/InventoryState) of the related quantity of items after the adjustment.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? toState;

  /// The Square-generated ID of the [Location](https://developer.squareup.com/reference/square_2023-12-13/objects/Location) where the related quantity of items is being tracked.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? locationId;

  /// The Square-generated ID of the [CatalogObject](https://developer.squareup.com/reference/square_2023-12-13/objects/CatalogObject) being tracked.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? catalogObjectId;

  /// The [type](https://developer.squareup.com/reference/square_2023-12-13/enums/CatalogObjectType) of the [CatalogObject](https://developer.squareup.com/reference/square_2023-12-13/objects/CatalogObject) being tracked.   The Inventory API supports setting and reading the `\"catalog_object_type\": \"ITEM_VARIATION\"` field value.  In addition, it can also read the `\"catalog_object_type\": \"ITEM\"` field value that is set by the Square Restaurants app.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? catalogObjectType;

  /// The number of items affected by the adjustment as a decimal string. Can support up to 5 digits after the decimal point.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? quantity;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  Money? totalPriceMoney;

  /// A client-generated RFC 3339-formatted timestamp that indicates when the inventory adjustment took place. For inventory adjustment updates, the `occurred_at` timestamp cannot be older than 24 hours or in the future relative to the time of the request.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? occurredAt;

  /// An RFC 3339-formatted timestamp that indicates when the inventory adjustment is received.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? createdAt;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  SourceApplication? source_;

  /// The Square-generated ID of the [Employee](https://developer.squareup.com/reference/square_2023-12-13/objects/Employee) responsible for the inventory adjustment.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? employeeId;

  /// The Square-generated ID of the [Team Member](https://developer.squareup.com/reference/square_2023-12-13/objects/TeamMember) responsible for the inventory adjustment.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? teamMemberId;

  /// The Square-generated ID of the [Transaction](https://developer.squareup.com/reference/square_2023-12-13/objects/Transaction) that caused the adjustment. Only relevant for payment-related state transitions.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? transactionId;

  /// The Square-generated ID of the [Refund](https://developer.squareup.com/reference/square_2023-12-13/objects/Refund) that caused the adjustment. Only relevant for refund-related state transitions.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? refundId;

  /// The Square-generated ID of the purchase order that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? purchaseOrderId;

  /// The Square-generated ID of the goods receipt that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  String? goodsReceiptId;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  InventoryAdjustmentGroup? adjustmentGroup;

  @override
  bool operator ==(Object other) => identical(this, other) || other is InventoryAdjustment &&
    other.id == id &&
    other.referenceId == referenceId &&
    other.fromState == fromState &&
    other.toState == toState &&
    other.locationId == locationId &&
    other.catalogObjectId == catalogObjectId &&
    other.catalogObjectType == catalogObjectType &&
    other.quantity == quantity &&
    other.totalPriceMoney == totalPriceMoney &&
    other.occurredAt == occurredAt &&
    other.createdAt == createdAt &&
    other.source_ == source_ &&
    other.employeeId == employeeId &&
    other.teamMemberId == teamMemberId &&
    other.transactionId == transactionId &&
    other.refundId == refundId &&
    other.purchaseOrderId == purchaseOrderId &&
    other.goodsReceiptId == goodsReceiptId &&
    other.adjustmentGroup == adjustmentGroup;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (id == null ? 0 : id!.hashCode) +
    (referenceId == null ? 0 : referenceId!.hashCode) +
    (fromState == null ? 0 : fromState!.hashCode) +
    (toState == null ? 0 : toState!.hashCode) +
    (locationId == null ? 0 : locationId!.hashCode) +
    (catalogObjectId == null ? 0 : catalogObjectId!.hashCode) +
    (catalogObjectType == null ? 0 : catalogObjectType!.hashCode) +
    (quantity == null ? 0 : quantity!.hashCode) +
    (totalPriceMoney == null ? 0 : totalPriceMoney!.hashCode) +
    (occurredAt == null ? 0 : occurredAt!.hashCode) +
    (createdAt == null ? 0 : createdAt!.hashCode) +
    (source_ == null ? 0 : source_!.hashCode) +
    (employeeId == null ? 0 : employeeId!.hashCode) +
    (teamMemberId == null ? 0 : teamMemberId!.hashCode) +
    (transactionId == null ? 0 : transactionId!.hashCode) +
    (refundId == null ? 0 : refundId!.hashCode) +
    (purchaseOrderId == null ? 0 : purchaseOrderId!.hashCode) +
    (goodsReceiptId == null ? 0 : goodsReceiptId!.hashCode) +
    (adjustmentGroup == null ? 0 : adjustmentGroup!.hashCode);

  @override
  String toString() => 'InventoryAdjustment[id=$id, referenceId=$referenceId, fromState=$fromState, toState=$toState, locationId=$locationId, catalogObjectId=$catalogObjectId, catalogObjectType=$catalogObjectType, quantity=$quantity, totalPriceMoney=$totalPriceMoney, occurredAt=$occurredAt, createdAt=$createdAt, source_=$source_, employeeId=$employeeId, teamMemberId=$teamMemberId, transactionId=$transactionId, refundId=$refundId, purchaseOrderId=$purchaseOrderId, goodsReceiptId=$goodsReceiptId, adjustmentGroup=$adjustmentGroup]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.id != null) {
      json[r'id'] = this.id;
    } else {
      json[r'id'] = null;
    }
    if (this.referenceId != null) {
      json[r'reference_id'] = this.referenceId;
    } else {
      json[r'reference_id'] = null;
    }
    if (this.fromState != null) {
      json[r'from_state'] = this.fromState;
    } else {
      json[r'from_state'] = null;
    }
    if (this.toState != null) {
      json[r'to_state'] = this.toState;
    } else {
      json[r'to_state'] = null;
    }
    if (this.locationId != null) {
      json[r'location_id'] = this.locationId;
    } else {
      json[r'location_id'] = null;
    }
    if (this.catalogObjectId != null) {
      json[r'catalog_object_id'] = this.catalogObjectId;
    } else {
      json[r'catalog_object_id'] = null;
    }
    if (this.catalogObjectType != null) {
      json[r'catalog_object_type'] = this.catalogObjectType;
    } else {
      json[r'catalog_object_type'] = null;
    }
    if (this.quantity != null) {
      json[r'quantity'] = this.quantity;
    } else {
      json[r'quantity'] = null;
    }
    if (this.totalPriceMoney != null) {
      json[r'total_price_money'] = this.totalPriceMoney;
    } else {
      json[r'total_price_money'] = null;
    }
    if (this.occurredAt != null) {
      json[r'occurred_at'] = this.occurredAt;
    } else {
      json[r'occurred_at'] = null;
    }
    if (this.createdAt != null) {
      json[r'created_at'] = this.createdAt;
    } else {
      json[r'created_at'] = null;
    }
    if (this.source_ != null) {
      json[r'source'] = this.source_;
    } else {
      json[r'source'] = null;
    }
    if (this.employeeId != null) {
      json[r'employee_id'] = this.employeeId;
    } else {
      json[r'employee_id'] = null;
    }
    if (this.teamMemberId != null) {
      json[r'team_member_id'] = this.teamMemberId;
    } else {
      json[r'team_member_id'] = null;
    }
    if (this.transactionId != null) {
      json[r'transaction_id'] = this.transactionId;
    } else {
      json[r'transaction_id'] = null;
    }
    if (this.refundId != null) {
      json[r'refund_id'] = this.refundId;
    } else {
      json[r'refund_id'] = null;
    }
    if (this.purchaseOrderId != null) {
      json[r'purchase_order_id'] = this.purchaseOrderId;
    } else {
      json[r'purchase_order_id'] = null;
    }
    if (this.goodsReceiptId != null) {
      json[r'goods_receipt_id'] = this.goodsReceiptId;
    } else {
      json[r'goods_receipt_id'] = null;
    }
    if (this.adjustmentGroup != null) {
      json[r'adjustment_group'] = this.adjustmentGroup;
    } else {
      json[r'adjustment_group'] = null;
    }
    return json;
  }

  /// Returns a new [InventoryAdjustment] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static InventoryAdjustment? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "InventoryAdjustment[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "InventoryAdjustment[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return InventoryAdjustment(
        id: mapValueOfType<String>(json, r'id'),
        referenceId: mapValueOfType<String>(json, r'reference_id'),
        fromState: mapValueOfType<String>(json, r'from_state'),
        toState: mapValueOfType<String>(json, r'to_state'),
        locationId: mapValueOfType<String>(json, r'location_id'),
        catalogObjectId: mapValueOfType<String>(json, r'catalog_object_id'),
        catalogObjectType: mapValueOfType<String>(json, r'catalog_object_type'),
        quantity: mapValueOfType<String>(json, r'quantity'),
        totalPriceMoney: Money.fromJson(json[r'total_price_money']),
        occurredAt: mapValueOfType<String>(json, r'occurred_at'),
        createdAt: mapValueOfType<String>(json, r'created_at'),
        source_: SourceApplication.fromJson(json[r'source']),
        employeeId: mapValueOfType<String>(json, r'employee_id'),
        teamMemberId: mapValueOfType<String>(json, r'team_member_id'),
        transactionId: mapValueOfType<String>(json, r'transaction_id'),
        refundId: mapValueOfType<String>(json, r'refund_id'),
        purchaseOrderId: mapValueOfType<String>(json, r'purchase_order_id'),
        goodsReceiptId: mapValueOfType<String>(json, r'goods_receipt_id'),
        adjustmentGroup: InventoryAdjustmentGroup.fromJson(json[r'adjustment_group']),
      );
    }
    return null;
  }

  static List<InventoryAdjustment> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <InventoryAdjustment>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = InventoryAdjustment.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, InventoryAdjustment> mapFromJson(dynamic json) {
    final map = <String, InventoryAdjustment>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = InventoryAdjustment.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of InventoryAdjustment-objects as value to a dart map
  static Map<String, List<InventoryAdjustment>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<InventoryAdjustment>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = InventoryAdjustment.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

