//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

/// Defines whether the event was generated by the Square Point of Sale.
class LoyaltyEventSource {
  /// Instantiate a new enum with the provided [value].
  const LoyaltyEventSource._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const SQUARE = LoyaltyEventSource._(r'SQUARE');
  static const LOYALTY_API = LoyaltyEventSource._(r'LOYALTY_API');

  /// List of all possible values in this [enum][LoyaltyEventSource].
  static const values = <LoyaltyEventSource>[
    SQUARE,
    LOYALTY_API,
  ];

  static LoyaltyEventSource? fromJson(dynamic value) => LoyaltyEventSourceTypeTransformer().decode(value);

  static List<LoyaltyEventSource> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <LoyaltyEventSource>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LoyaltyEventSource.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [LoyaltyEventSource] to String,
/// and [decode] dynamic data back to [LoyaltyEventSource].
class LoyaltyEventSourceTypeTransformer {
  factory LoyaltyEventSourceTypeTransformer() => _instance ??= const LoyaltyEventSourceTypeTransformer._();

  const LoyaltyEventSourceTypeTransformer._();

  String encode(LoyaltyEventSource data) => data.value;

  /// Decodes a [dynamic value][data] to a LoyaltyEventSource.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  LoyaltyEventSource? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'SQUARE': return LoyaltyEventSource.SQUARE;
        case r'LOYALTY_API': return LoyaltyEventSource.LOYALTY_API;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [LoyaltyEventSourceTypeTransformer] instance.
  static LoyaltyEventSourceTypeTransformer? _instance;
}

