//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class RetrieveGiftCardFromNonceRequest {
  /// Returns a new [RetrieveGiftCardFromNonceRequest] instance.
  RetrieveGiftCardFromNonceRequest({
    required this.nonce,
  });

  /// The payment token of the gift card to retrieve. Payment tokens are generated by the  Web Payments SDK or In-App Payments SDK.
  String nonce;

  @override
  bool operator ==(Object other) => identical(this, other) || other is RetrieveGiftCardFromNonceRequest &&
    other.nonce == nonce;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (nonce.hashCode);

  @override
  String toString() => 'RetrieveGiftCardFromNonceRequest[nonce=$nonce]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'nonce'] = this.nonce;
    return json;
  }

  /// Returns a new [RetrieveGiftCardFromNonceRequest] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static RetrieveGiftCardFromNonceRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "RetrieveGiftCardFromNonceRequest[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "RetrieveGiftCardFromNonceRequest[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return RetrieveGiftCardFromNonceRequest(
        nonce: mapValueOfType<String>(json, r'nonce')!,
      );
    }
    return null;
  }

  static List<RetrieveGiftCardFromNonceRequest> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <RetrieveGiftCardFromNonceRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = RetrieveGiftCardFromNonceRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, RetrieveGiftCardFromNonceRequest> mapFromJson(dynamic json) {
    final map = <String, RetrieveGiftCardFromNonceRequest>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = RetrieveGiftCardFromNonceRequest.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of RetrieveGiftCardFromNonceRequest-objects as value to a dart map
  static Map<String, List<RetrieveGiftCardFromNonceRequest>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<RetrieveGiftCardFromNonceRequest>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = RetrieveGiftCardFromNonceRequest.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'nonce',
  };
}

